//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _CW_NETMF_ONEWIRE_H_
#define _CW_NETMF_ONEWIRE_H_

#include <TinyCLR_Interop.h>
struct Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire
{
    static const int FIELD__disposed = 1;
    static const int FIELD__pin = 2;

    TINYCLR_NATIVE_DECLARE(_ctor___VOID__MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuPin);
    TINYCLR_NATIVE_DECLARE(Reset___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Read___I4__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(ReadBit___U1);
    TINYCLR_NATIVE_DECLARE(ReadByte___U1);
    TINYCLR_NATIVE_DECLARE(Write___VOID__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(WriteBit___VOID__U1);
    TINYCLR_NATIVE_DECLARE(WriteByte___VOID__U1);
    TINYCLR_NATIVE_DECLARE(Search___I4__SZARRAY_U1__I4__I4);
    TINYCLR_NATIVE_DECLARE(ComputeCRC___STATIC__U1__SZARRAY_U1__I4__I4__U1);
    TINYCLR_NATIVE_DECLARE(ComputeCRC16___STATIC__U2__SZARRAY_U1__I4__I4__U2);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CW_NETMF_OneWire;

#endif  //_CW_NETMF_ONEWIRE_H_
