//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "CW_NETMF_OneWire.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::_ctor___VOID__MicrosoftSPOTHardwareMicrosoftSPOTHardwareCpuPin,
    NULL,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::Reset___BOOLEAN,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::Read___I4__SZARRAY_U1__I4__I4,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::ReadBit___U1,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::ReadByte___U1,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::Write___VOID__SZARRAY_U1__I4__I4,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::WriteBit___VOID__U1,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::WriteByte___VOID__U1,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::Search___I4__SZARRAY_U1__I4__I4,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::ComputeCRC___STATIC__U1__SZARRAY_U1__I4__I4__U1,
    Library_CW_NETMF_OneWire_CW_NETMF_Hardware_OneWire::ComputeCRC16___STATIC__U2__SZARRAY_U1__I4__I4__U2,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_CW_NETMF_OneWire =
{
    "CW.NETMF.OneWire", 
    0x0A1BB949,
    method_lookup
};

